name: CI

on:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.20.x, 1.21.x, 1.22.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
            version: '~> v2'
            args: build --clean --verbose
            #args: release --clean
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



